### ISSUE TITLE
[BUG] blank dashboard

### ISSUE THREAD

**Issue by gomzy2k23** [bearlike/REMS-For-Organisations#61]
`http://localhost/rems/members/dashboard.php` - this page goes blank after logged in as admin  - no errors are displayed. im using iis server with latest php. 

there are lots of errors in the sql - may be needs to be updated.

http://localhost/rems/public/cds-public.php?event=s

```
PHP Warning:  Undefined variable $isInter in C:\inetpub\wwwroot\rems\public\cds-public.php on line 88
PHP Warning:  Undefined variable $isInter in C:\inetpub\wwwroot\rems\public\cds-public.php on line 236
PHP Warning:  Undefined variable $isInter in C:\inetpub\wwwroot\rems\public\cds-public.php on line 264
PHP Warning:  Undefined variable $isInter in C:\inetpub\wwwroot\rems\public\cds-public.php on line 301
```

http://localhost/rems/members/forgot-password.php

PHP Warning:  require(../src/PHPMailer/Exception.php): Failed to open stream: No such file or directory in C:\inetpub\wwwroot\rems\members\forgot-password.php on line 8
PHP Fatal error:  Uncaught Error: Failed opening required '../src/PHPMailer/Exception.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\rems\members\forgot-password.php:8
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\rems\members\forgot-password.php on line 8

PHP Warning:  require(../src/PHPMailer/Exception.php): Failed to open stream: No such file or directory in C:\inetpub\wwwroot\rems\members\forgot-password.php on line 8
PHP Fatal error:  Uncaught Error: Failed opening required '../src/PHPMailer/Exception.php' (include_path='.;C:\php\pear\pear') in C:\inetpub\wwwroot\rems\members\forgot-password.php:8
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\rems\members\forgot-password.php on line 8

**Comment by bearlike** [comment]
- Can you share more details about your setup? (PHP version, Database Version, Deployment, etc.). Based on what is currently available, it seems like your deployment is unable to access PHPMailer. This mostly indicates a permission issue or incorrect installation. We suggest you try using `php:7.2` instead of the latest version. If you're new to setting up web servers, you may follow along the instructions available in `README.md`, [`Dockerfile`](https://github.com/bearlike/REMS-For-Organisations/blob/master/Dockerfile), and [`docker-compose.yml`](https://github.com/bearlike/REMS-For-Organisations/blob/master/docker-compose.yml)

> no errors are displayed
- By default, PHP may be configured to not display errors on the browser. The `error_log` directive in the `php.ini` file determines the location where PHP errors are logged. You can share the specified log file with us.

> there are lots of errors in the sql - may be needs to be updated.
- I do not see any error log related to the database. If there are any, please do share.
---
**Also, please follow the bug reporting template. It's posted so that we can get the whole picture in one go.**

**Comment by gomzy2k23** [comment]
i have check phpmailer - i manage to fix it. Pear was not enable. 

i set php error reporting on - now i get this error after login as admin: 
http://localhost/rems/members/validate.php
` **could not find driver**`

**Comment by bearlike** [comment]
@gomzy2k23, that is not the complete error log. As I have previously mentioned:

> By default, PHP may be configured to not display errors on the browser.

Kindly follow the links below to find your error logs. The location varies according to your setup. If you are new to this, we advise you to refer to the following articles and search the internet for relevant information:

1. [Where does PHP store the error log? (PHP 5, Apache, FastCGI, and cPanel)](https://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php-5-apache-fastcgi-and-cpanel)
2. [Display All PHP Errors: Basic & Advanced Usage](https://stackify.com/display-php-errors/)
3. [PHP error logs guide](https://stackify.com/php-error-logs-guide/)

In my best guess, the error "could not find driver" could indicate that `pdo_mysql` is not installed. Kindly install `pdo_mysql` and check the issue. To continue this discussion any further, we will need the error logs.

**Comment by gomzy2k23** [comment]
i tried to use iis and xampp . both stuck on a blank page after log in with username and password admin admin.

[access.log](https://github.com/bearlike/REMS-For-Organisations/files/11562014/access.log)
[error.log](https://github.com/bearlike/REMS-For-Organisations/files/11562016/error.log)
[install.log](https://github.com/bearlike/REMS-For-Organisations/files/11562017/install.log)
[ssl_request.log](https://github.com/bearlike/REMS-For-Organisations/files/11562018/ssl_request.log)

**Comment by bearlike** [comment]
The logs show no relevant errors, suggesting issues with the REMS setup or web server stack installation. Issues outside REMS deployment are beyond our project's scope. Please update this thread if a relevant bug is discovered.
